### ISSUE TITLE
ksort() expects parameter 1 to be array, null given

### ISSUE THREAD

**Issue by azuddin** [thiagocordeiro/laravel-translator#1]
<img width="387" alt="screen shot 2018-01-14 at 11 37 04 pm" src="https://user-images.githubusercontent.com/8788888/34917617-ed68de8c-f983-11e7-8db0-2ccd14196469.png">

**Comment by thiagocordeiro** [comment]
You probably didn't create translation files at `app/resources/lang/` or it has invalid json, anyway I we should cover this scenario to show a friendly message
