### ISSUE TITLE
Scan vuejs files for translations

### ISSUE THREAD

**Issue by AMAFsoft** [thiagocordeiro/laravel-translator#26]
In my *.vue files I'm using the same translation function __('') ;
is there a way to add `vue` files to the list of scannable files? 
Example : 

```
<template>
  <div>{{__('Hello')}}</div>
</template>
```

**Comment by AMAFsoft** [comment]
This solution works great for me:
`$files = glob_recursive("{$path}/*.{php,vue}", GLOB_BRACE);`
But if you could add it officially to this package would be great.

**Comment by thiagocordeiro** [comment]
Yes, this is the solution, but I guess we shouldn’t scan vue files by default,
can you create a PR extending the configuration in src/Framework/config.php?

**Comment by AMAFsoft** [comment]
Done!
#27

**Comment by thiagocordeiro** [comment]
Available on version [v1.1.0](https://github.com/thiagocordeiro/laravel-translator/releases/tag/v1.1.0)
