### ISSUE TITLE
Keys with escaped single or double quote (', ") do not work

### ISSUE THREAD

**Issue by yya** [thiagocordeiro/laravel-translator#4]
When having single or double quotes in the keys the scanner does not work properly even if the quotes are escaped with '\'.

Using the regex using in $stringPattern from this package can help:
https://github.com/barryvdh/laravel-translation-manager/blob/master/src/Manager.php#L172

**Comment by pedroshift** [comment]
changes coming at https://github.com/thiagocordeiro/laravel-translator/tree/bugfix/ISSUE-4-escape-quotes

**Comment by bensinjin** [comment]
Work around (blade template):
```
{{ __('You :cant choose :other. ', ['cant' => 'can\'t', 'other' => '"Other"']) }}
```

**Comment by leetdev** [comment]
> Work around (blade template):
> 
> ```
> {{ __('You :cant choose :other. ', ['cant' => 'can\'t', 'other' => '"Other"']) }}
> ```

This will still have the issue with the strings `can't` and `"Other"` (or anything else you might use with this workaround) not being translated though.
